version: "2"
services:
  web:
    build: .
    container_name: twitter_web
    volumes:
    - ./:/var/web
    ports:
    - "9000:9000"
    depends_on:
    - mysqldb

  nginx:
    image: nginx:latest
    container_name: twitter_nginx
    ports:
    - "80:80"
    command: /bin/sh -c "cp /var/web/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
    - ./:/var/web
    depends_on:
    - web

  mysqldb:
    image: mysql:5.7
    container_name: twitter_mysql
    env_file:
    - ".env"
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_DATABASE}
    ports:
    - "3306:3306"
